name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      # 1. دریافت کد
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. نصب Python و Buildozer
      - name: Set up Python and Buildozer
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: |
          python -m pip install --upgrade pip
          pip install buildozer Cython virtualenv

      # 3. نصب Java
      - name: Install Java
        run: sudo apt-get install -y openjdk-17-jdk

      # 4. نصب ابزارهای مورد نیاز لینوکس
      - name: Install Linux Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip git zip build-essential libstdc++6

      # 5. نصب Android SDK، Build Tools و NDK و پذیرش لایسنس‌ها
      - name: Install Android SDK & Build Tools
        run: |
          mkdir -p $HOME/android-sdk
          cd $HOME/android-sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O tools.zip
          unzip tools.zip -d cmdline-tools
          mv cmdline-tools/cmdline-tools cmdline-tools/latest
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          yes | sdkmanager --licenses || true
          sdkmanager "platforms;android-33" "platform-tools" "build-tools;33.0.2" "ndk;25.2.9519653"
          export PATH=$ANDROID_HOME/build-tools/33.0.2:$ANDROID_HOME/ndk/25.2.9519653:$PATH

      # 6. پاکسازی ساخت قبلی
      - name: Clean previous builds
        run: |
          rm -rf ~/.buildozer
          buildozer android clean || true

      # 7. کامپایل با Buildozer
      - name: Build APK
        run: buildozer android debug

      # 8. آپلود APK به GitHub Artifacts
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Kos_VPN-APK
          path: bin/*.apk
