name: Build Android APK (Final Correct Version)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17, Python 3.10 and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk git zip unzip build-essential libstdc++6 autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtcl8.6 libsqlite3-dev libssl-dev libgdbm-dev libbz2-dev libreadline-dev libffi-dev liblzma-dev
          python -m pip install --upgrade pip
          pip install buildozer cython

      - name: Setup Android SDK and NDK
        uses: android-actions/setup-android@v3

      - name: Configure Buildozer and Run Build
        run: |
          echo "Updating buildozer.spec with correct SDK and NDK paths..."
          # از دستور sed برای پیدا کردن و جایگزینی مسیرها در فایل spec استفاده می‌کنیم
          # این کار تضمین می‌کند که buildozer از SDK و NDK نصب شده توسط ما استفاده کند
          sed -i "s|^#*\(android\.sdk_path\s*=\s*\).*$|android.sdk_path = $ANDROID_SDK_ROOT|" buildozer.spec
          sed -i "s|^#*\(android\.ndk_path\s*=\s*\).*$|android.ndk_path = $ANDROID_NDK_HOME|" buildozer.spec

          echo "--- Verifying buildozer.spec content ---"
          # محتوای فایل را نمایش می‌دهیم تا از صحت تغییرات مطمئن شویم
          cat buildozer.spec
          echo "----------------------------------------"

          echo "Running build command..."
          # دستور بیلد را با جزئیات کامل لاگ اجرا می‌کنیم
          buildozer -v android debug

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Kos_VPN-APK
          path: bin/*.apk
          if-no-files-found: error
