name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            git \
            unzip \
            openjdk-17-jdk \
            zip \
            libffi-dev \
            libssl-dev \
            liblzo2-dev \
            libsqlite3-dev \
            zlib1g-dev

      - name: Remove system NDKs (to avoid conflicts)
        run: |
          sudo rm -rf /usr/local/lib/android/sdk/ndk/*
          echo "✅ Removed pre-installed NDKs"

      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer cython

      - name: Build APK
        env:
          ANDROIDSDK: /home/runner/.buildozer/android/platform/android-sdk
          ANDROIDNDK: /home/runner/.buildozer/android/platform/android-ndk-r25b
          ANDROIDAPI: 31
          ANDROIDMINAPI: 21
          PATH: /home/runner/.buildozer/android/platform/apache-ant-1.9.4/bin:$PATH
        run: |
          buildozer android debug
