name: Build Android APK (Auto-Correcting Version)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17 and Python 3.10
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip build-essential autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtcl8.6 libsqlite3-dev libssl-dev libgdbm-dev libbz2-dev libreadline-dev libffi-dev liblzma-dev
          python -m pip install --upgrade pip
          pip install buildozer cython

      - name: Setup Android SDK and NDK
        uses: android-actions/setup-android@v3

      - name: Correct and Prepare buildozer.spec File
        run: |
          echo "Correcting buildozer.spec..."
          # 1. اصلاح دامنه پکیج (حذف / و استفاده از فرمت استاندارد)
          sed -i "s|^package\.domain\s*=\s*.*$|package.domain = org.kosvpn|" buildozer.spec
          
          # 2. اصلاح نام پکیج (تبدیل به حروف کوچک)
          sed -i "s|^package\.name\s*=\s*.*$|package.name = kosvpn|" buildozer.spec
          
          # 3. اصلاح و تکمیل نیازمندی‌ها (اضافه کردن hostopenssl)
          sed -i "s|^requirements\s*=\s*.*$|requirements = python3,kivy==2.3.0,https://github.com/kivymd/KivyMD/archive/master.zip,pillow,hostopenssl,openssl|" buildozer.spec

          echo "--- Verifying buildozer.spec content after corrections ---"
          cat buildozer.spec
          echo "--------------------------------------------------------"

      - name: Build with Buildozer
        run: buildozer -v android debug

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Kos_VPN-APK
          path: bin/*.apk
          if-no-files-found: error
          
