name: Build Android APK (Final Version)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies (Linux, Java, Buildozer)
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk git zip unzip build-essential libstdc++6
          python -m pip install --upgrade pip
          pip install buildozer cython

      - name: Set up Android SDK and NDK
        run: |
          # Create SDK directories and download command-line tools
          mkdir -p $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O $HOME/tools.zip
          unzip -q $HOME/tools.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest

          # Set environment variables for all subsequent steps
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH
          
          # Accept licenses and install required packages
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses > /dev/null
          $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager "platforms;android-33" "platform-tools" "build-tools;33.0.2" "ndk;25.2.9519653"
          
          # Add the just-installed build-tools to the PATH for all subsequent steps
          echo "$HOME/android-sdk/build-tools/33.0.2" >> $GITHUB_PATH
          
      - name: Configure and Build APK with Buildozer
        run: |
          # Clean previous build artifacts, if any
          buildozer android clean || true
          
          # Run the build
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Kos_VPN-APK
          path: bin/*.apk
          if-no-files-found: error
