name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Buildozer & Cython
        run: |
          python -m pip install --upgrade pip
          pip install buildozer Cython

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip git zip build-essential libstdc++6

      - name: Install Java
        run: sudo apt-get install -y openjdk-17-jdk

      - name: Install Android SDK, NDK and Build Tools
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O tools.zip
          unzip tools.zip -d cmdline-tools
          mv cmdline-tools/cmdline-tools cmdline-tools/latest
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH

          # نصب نسخه پایدار build-tools و platform
          yes | sdkmanager --licenses
          sdkmanager "platforms;android-33" "platform-tools" "build-tools;33.0.2" "ndk;25.2.9519653"

      - name: Add build-tools to PATH
        run: |
          export PATH=$HOME/android-sdk/build-tools/33.0.2:$PATH
          echo "AIDL path: $(which aidl || echo 'not found')"

      - name: Clean previous builds
        run: |
          rm -rf ~/.buildozer
          buildozer android clean || true

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Kos_VPN-APK
          path: bin/*.apk
