name: Build Android APK

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Buildozer prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip \
            openjdk-17-jdk python3-pip \
            autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          git --version

      - name: Remove system NDKs (avoid conflicts)
        run: sudo rm -rf /usr/local/lib/android/sdk/ndk/*

      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer cython

      - name: Build APK
        env:
          ANDROIDSDK: /home/runner/.buildozer/android/platform/android-sdk
          ANDROIDNDK: /home/runner/.buildozer/android/platform/android-ndk-r25b
          ANDROIDAPI: 31
          ANDROIDMINAPI: 21
        run: |
          buildozer android debug
