name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            python3 \
            python3-pip \
            python3-setuptools \
            python3-wheel \
            python3-virtualenv \
            build-essential \
            ccache \
            libncurses5 \
            libtinfo5 \
            zlib1g-dev \
            libffi-dev \
            libssl-dev \
            libsqlite3-dev \
            libjpeg-dev \
            libpng-dev \
            libfreetype6-dev \
            libblas-dev \
            liblapack-dev \
            gfortran

      - name: Install buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Kos_VPN-APK
          path: bin/*.apk

      - name: Create Release and Upload APK
        uses: softprops/action-gh-release@v1
        with:
          files: bin/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
