name: Build Android APK (Correct Final Version)

on: [push]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK and NDK
        uses: android-actions/setup-android@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Buildozer and dependencies
        run: |
          pip install --upgrade pip
          pip install buildozer cython

      # --- مرحله کلیدی و اصلاح شده ---
      - name: Configure Buildozer and Run Build
        run: |
          echo "Updating buildozer.spec with correct SDK and NDK paths..."
          # از دستور sed برای پیدا کردن و جایگزینی مسیرها در فایل spec استفاده می‌کنیم
          sed -i "s|^#*\(android\.sdk_path\s*=\s*\).*$|\1$ANDROID_SDK_ROOT|" buildozer.spec
          sed -i "s|^#*\(android\.ndk_path\s*=\s*\).*$|\1$ANDROID_NDK_HOME|" buildozer.spec

          echo "--- Verifying buildozer.spec content ---"
          # محتوای فایل را نمایش می‌دهیم تا از صحت تغییرات مطمئن شویم
          cat buildozer.spec
          echo "----------------------------------------"

          echo "Running build command..."
          buildozer -v android debug

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
          if-no-files-found: error
